apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ediscan.fullname" . }}
  labels:
    {{- include "ediscan.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLASK_SECRET_KEY: {{ .Values.secrets.flaskSecretKey | quote }}

